version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
